### ISSUE TITLE
Redgate has removed the mvp landing page

### ISSUE THREAD

**Issue by BenjaminAbt** [xavierdecoster/mvpperks#52]
Redgate has removed the landing page and now has a special mvp email address (only visible to active MVPs, internal page).

https://github.com/xavierdecoster/mvpperks/blob/e0a0b14b5027e30476e5889379a588c485a24f9d/_data/perks.yml#L17

Remove the entry or keep it with invalid url?

**Comment by xavierdecoster** [comment]
Thanks for reporting!

Is there a blog post or other public page we can refer to where MVPs can find sufficient details how to obtain the offer?
If nothing public, we should remove the offer from this page. You want to take a stab at it?
